### ISSUE TITLE
Warnung/Fehler nach Update auf PHP 7.3

### ISSUE THREAD

**Issue by marcel293** [sebschlicht/com_nuliga#11]
Hallo Sebastian,

nach dem notwendigen Update auf PHP 7.3 bekomme ich folgende Fehlermeldung auf der Webseite:

**_Warnung
Failed to parse HTML of NuLiga team #2 from URL ''!

Fehler
COM_NULIGA_NULIGA_UPDATE_ERROR_**

Stelle ich auf PHP 7.2 zurück, funktioniert es wieder.

Danke und Gruß
Marcel

**Comment by marcel293** [comment]
Hallo Sebastian,

gibt es etwas Neues zum Thema?
Heute läuft der 7.2. Support beim Hoster aus. Daher kann habe ich das Problem erneut und kann auch nicht mehr auf 7.2 zurückstellen. Leider funktionieren somit alle Tabellen des Vereins nicht. 

Danke und Gruß
Marcel

**Comment by sebschlicht** [comment]
Hallo Marcel,

ich arbeite zeitlich bedingt schon eine Weile nicht mehr an der Komponente, da ich sie private nicht mehr selbst verwende.

Hast du die URL im Rahmen dieses Issue zensiert oder wird sie tatsächlich leer ausgegeben?
Bisher bin ich von einem Problem in simpleHtmDom ausgegangen, aber eine leere URL würde natürlich auf eine Inkompatibilität in meinem Code hinweisen.

Grüße
Sebastian

**Comment by marcel293** [comment]
Hallo Sebastian,

danke für deine Antwort. Das ist natürlich schade. Ich nutze die Komponente für fast 20 Mannschaften.

Die Fehlermeldung ist aus dem Frontend kopiert.
[Link zu einem Beispiel](http://holzdorfer.de/index.php/tabelle-maenner)

Wäre super, wenn du mal schauen könntest.

Vielen Dank und **bleib gesund!**
Marcel

**Comment by lukas1206** [comment]
Hallo zusammen, ich habe dasselbe Problem. 
Ich hab mir das Ganze mal genauer angeschaut und vermute das es daran liegt das der PHP Core ab Version 7.3 PCRE2 verwendet.
Leider konnte ich das Problem bisher mit Regex Anpassungen auch nicht beheben.

Viele Grüße ,
Lukas

**Comment by lukas1206** [comment]
Hi nochmal,
ich hab die Komponente bei mir wieder zum laufen gebracht, im Großen und Ganzen waren es nur Regex Anpassungen.
Im Anhang hier meine überarbeitete simple_html_dom.php File.
Ich hoffe das hilft :)
[simple_html_dom.zip](https://github.com/sebschlicht/com_nuliga/files/5826496/simple_html_dom.zip)
Viele Grüße,
Lukas

**Comment by marcel293** [comment]
Hallo Lukas,

vielen vielen Dank für deine Mühen!
Bei mir hat es auch funktioniert!
Du hast mir eine Menge Arbeit erspart!!!

Viele Grüße und bleibt gesund!
Marcel
