### ISSUE TITLE
Zeitpläne werden nicht dargestellt /eingelesen.

### ISSUE THREAD

**Issue by snookersonic** [sebschlicht/com_nuliga#2]
Leider konnte ich keine Beschreibung der PHP Version finden. Ist 7.2 zu hoch?
auf alle fälle kann ich nicht letzte Ergebnisse und nächste Spiele anzeigen lassen.

UND! Weltklasse wäre wenn man die Mannschaftsspielpläne als ICAL anzeigen könnte...

Gruß
Litho

**Comment by sebschlicht** [comment]
Habe ich in der README ergänzt.
Mit ICAL habe ich mich bisher nicht beschäftigt. Wenn du kannst, gerne forken und einen Pull-Request schicken. Ansonsten ggf. im Oktober im Rahmen einer neuen Version.

**Comment by sebschlicht** [comment]
PHP 7 wird nun nativ unterstützt, ist entsprechend in der README vermerkt. ICAL ist davon unabhängig, bitte bei Bedarf ein separates Issue eröffnen. Closed.
