### ISSUE TITLE
Hallennummer Verlinken

### ISSUE THREAD

**Issue by gogicomputers** [sebschlicht/com_nuliga#4]
Gibt es eine Möglichkeit, die Hallennummer zu verlinken?
Kann man die Darstellung des Spielplans beeinflussen? Lässt das plugin oder die Komponente Overrides zu?

**Comment by sebschlicht** [comment]
Im Moment nicht aber ein anderer Nutzer (der mir persönlich schrieb und dazu leider kein Issue erstellt hat) arbeitet wohl an dem Feature. Ich versuche, ihn in das Gespräch zu integrieren.
Ab Oktober hätte ich wieder Kapazitäten frei, mich dem selbst zu widmen.

**Comment by sebschlicht** [comment]
Irgendwie habe ich beim letzten mal nur die erste Zeile deines Posts gelesen. Natürlich kannst du wie gewohnt Layout-Overrides nutzen, um die [Darstellung des Spielplans](https://github.com/sebschlicht/plg_nuliga/blob/master/layouts/schedule.php) zu beeinflussen. Das Layout ist allerdings nicht Teil der Komponente sondern des [Plugins](https://github.com/sebschlicht/plg_nuliga).

**Comment by gogicomputers** [comment]
Wie kann ich das Override erstellen, ich bekomme das irgendwie nicht hin und wenn ich in die nuliga.php des Plugins hineinschaue finde ich keinen Code, wo das Override geladen wird.

**Comment by sebschlicht** [comment]
Dazu gibt es keinen Code, ich rede von den [Overrides die Joomla! nativ unterstützt](https://docs.joomla.org/Layout_Overrides_in_Joomla/de#Plugin_Alternative_Layouts_.28Overriding_a_Plugin.29). Oder übersehe ich hier gerade was und die Layouts sind nicht overridable?

**Comment by sebschlicht** [comment]
Ahja, da habe ich die falsche Methodik benutzt. Fixed in [0.2.0](https://github.com/sebschlicht/plg_nuliga/releases/tag/v0.2.0).
