### ISSUE TITLE
Die NuLiga-Tabelle kann zurzeit nicht angezeigt werden.

### ISSUE THREAD

**Issue by wienni112** [sebschlicht/com_nuliga#5]
Hi, ich wollte das Joomla plugin für unseren Handballverein einsetzen. 
Wir nutzen Joomla 3 in der neusten version unter PHP 7.2.
Ich bekomme im Artikel folgende Meldung: Die NuLiga-Tabelle kann zurzeit nicht angezeigt werden. In den SQL Tabellen ist kein Inhalt zu finden, bis auf die Mannschaft die ich angelegt habe. Muss zum abrufen der Daten ein script ausgeführt werden? 

Die Parser habe ich auf 1.9 aktualisiert. Hat aber leider keine Besserung ergeben. 

Gibt es noch was spezielles zu beachten? 

Mit freundlichen Grüßen 
Wienni

**Comment by gogicomputers** [comment]
Hast du die Komponente und das Plugin installiert?

**Comment by wienni112** [comment]
Komponente und Plugin habe ich über das Backend Automatisch Installieren lassen. 
Und sind nochmal zusätzlich von mir aktiviert worden. 
Also nach meinem Verständnis sollte alles funktionieren. 
Als Liga-Link habe ich folgendes angegeben: 
https://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/groupPage?championship=Darmstadt+19%2F20&group=241016

Ich bekomme im Backend unter Mannschaft bearbeiten auch keine Aktualisierung angezeigt. 
Steht alles auf 0000-00-00 00:00:00

**Comment by sebschlicht** [comment]
Das liegt vermutlich an der PHP-Version. Die Komponente war mit PHP 7 nicht kompatibel. Einige Nutzer haben das manuell behoben, die aktuelle Version ist mittlerweile allerdings auch mit PHP 7 kompatibel.

Aktualisiere bitte mal Komponente und Plugin, eventuell behebt das dein Problem.

**Comment by wienni112** [comment]
Hi, danke für das update. 
Hat leider kein erfolg gebracht. 
Plugin und Modul neu installiert, ergaben keine Änderung. 
Bei unserem Joomla verwenden wir bootstrap, könnte das ein Problem sein?

Gruß Wienni

**Comment by sebschlicht** [comment]
Ich denke, mittlerweile habt ihr längst eine andere Lösung aber: Bootstrap stellt kein Problem dar. Ohne irgendwelche Fehlermeldungen o.ä. käme man allerdings auch heute nicht weiter.

**Comment by wienni112** [comment]
Hallo, habe leider noch keine alternative gefunden. 
Aktuell geht es noch nichts. 
Habe versucht selbst nach fehlern zu suchen konnte aber in keiner log was entdecken. 
Kannst du mir sagen wie du beim debuggen vorgehst? 

Kannst du mir eine Liga nennen die mit deinem Modul funktioniert? 
Vielleicht liegt es auch am verband. 
Hier der Link von der Gewünschten Mannschaft. 
https://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/teamPortrait?teamtable=1711213&pageState=vorrunde&championship=Darmstadt+20%2F21&group=260603

Gruß Wienni

**Comment by wienni112** [comment]
Habe mein fehler gefunden. Funktioniert jetzt! 

Danke für die unterstützung.
