### ISSUE TITLE
Mehrere PHP Feher

### ISSUE THREAD

**Issue by gogicomputers** [sebschlicht/com_nuliga#8]
Ich bekomme auf der Seite https://www.tsv-schnelldorf.de/handball/damen-i.html folgende 3 PHP-Fehler gefühlt 1000mal angezeigt:
Warning: preg_match(): Compilation failed: invalid range in character class at offset 4 in /www/htdocs/w00acc28/administrator/components/com_nuliga/libraries/nuliga/parser/simple_html_dom.php on line 1367

Warning: preg_match_all(): Compilation failed: invalid range in character class at offset 4 in /www/htdocs/w00acc28/administrator/components/com_nuliga/libraries/nuliga/parser/simple_html_dom.php on line 687

Warning: Invalid argument supplied for foreach() in /www/htdocs/w00acc28/administrator/components/com_nuliga/libraries/nuliga/parser/simple_html_dom.php on line 694

Die Fehler werden mit folgender Häufigkeit angezeigt:
Zeile 1367: 559
Zeile 687: 2
Zeile 694: 2

Kann es damit zu tun haben, dass die Liga-Spiele unterbruchen sind und im Datumsfeld auf nuLiga "Termin Offen" angezeigt wird? Unterhalb der Fehler wird die Tabelle und der Spielplan richtig angezeigt, nur eben mit den "alten" Terminen.

**Comment by sebschlicht** [comment]
Bei Kompilationsproblemen würde ich als erstes auf eine inkompatible PHP-Version setzen, ohne mich mit irgendwelchen Details auseinanderzusetzen. Welche Version ist denn auf dem Server im Einsatz?

Ansonsten: Sollte sich die HTML-Struktur der Seite geändert haben, was absolut vorkommen kann, würde ich definitiv Fehler erwarten. Dann wäre meine Erwartungshaltung jedoch, eine zielgerichtetere Fehlermeldung zu erhalten.

**Comment by gogicomputers** [comment]
Die Seite läuft auf PHP 7.3. Beim letzten Joomla update wurde ich darauf hingewiesen, dass PHP 7.2 ausläuft. Ich habe jetzt wieder auf PHP 7.2 umgestellt und jetzt tritt der fehler nicht mehr auf. Kommt in der nächsen Version eine PHP 7.3 Unterstüzung?

**Comment by sebschlicht** [comment]
Verstehe. Das können wir so machen, dann würde ich am Wochenende mal den DOM-Parser aktualisieren, sodass er mit der neusten PHP-Version kompatibel ist. Das wird dann auch mit 7.3 kombinierbar sein.

**Comment by sebschlicht** [comment]
Ich würde das Ticket schließen wollen. Beidseitig seit 1+ Jahr kein Update. Mein letzter Stand: nicht reproduzierbar. Bei mir lief es auf PHP7+ ohne Anstand.

**Comment by gogicomputers** [comment]
Der Fehler kam nach der Umstellung auf PHP 7.3. Ich hab auf dein Anraten hin wieder auf PHP 7.2 umgestellt, damit hat es wieder ohne Fehler läuft. Hast das Update vom DOM-Praser durchgeführt?

**Comment by sebschlicht** [comment]
Es gab damals ein Update von 1.9 auf 1.9.1, das hatte ich im Sinne von Semantic Versioning als nicht relevant erachtet. Kannst du prüfen, ob das ggf. doch Besserung bringt?
Dazu nimmst du einfach den [DOM-Parser in Version 1.9.1](https://sourceforge.net/projects/simplehtmldom/files/simplehtmldom/1.9.1/) und packst die entpackte PHP-Datei auf deinem Server in das Verzeichnis des installierten Plugins: `/administrator/components/com_nuliga/libraries/nuliga/parser/`.

Wenn das klappt, würde ich das als neue Version releasen. Wenn du das nicht selbst ausprobieren möchtest, könnte ich nochmal eine Testinstanz aufsetzen oder auf Verdacht releasen. Würde das aber lieber vorher getestet wissen.

**Comment by gogicomputers** [comment]
Ich habe die PHP Datei ersetzt. Momentan bekomme ich keine Fehler mehr angezeigt.
